# yet another markup language or YAML Ain't Markup Language, watch your spacing!
# Spring looks for application.properties and application.yaml (or application.yml) for Spring Boot properties
# YAML tends to be easier to read regarding data structures and used widely

# Profile names xxxx are given the by the name which follows application-xxxxx.yml or application-xxxxx.properties

# Enable a profile (instead of spring.profiles.active=EN); change EN to/from DE to allow -EN or -DE to override

# Mapping services:
# To explicitly enable 'map', replace 'springDataJPA' with 'map' (map is also part of 'default')

# MySQL connections are established when profile is set to 'dev' or 'prod', and 'springDataJPA'
# Running from a non-SQL non-persistent DB (h2) is set using 'h2' and 'map'

spring:
  profiles:
    active: EN, springDataJPA, dev

#spring:
#  profiles:
#    active: EN, map, h2

# equivalent to srmdatabase.customMessage=All credentials successfully loaded (this is the default if profiles
# are commented out)
#srmdatabase:
#  customMessage: "All good!"

---

# note that strings with special characters are best enclosed in " "
# for more info, go to https://yaml.org/