# yet another markup language or YAML Ain't Markup Language, watch your spacing!
# Spring looks for application.properties and application.yaml (or application.yml) for Spring Boot properties
# YAML tends to be easier to read regarding data structures and used widely

# equivalent to srmdatabase.customMessage
srmdatabase:
  customMessage: All credentials successfully loaded

# note that strings with special characters are best enclosed in " "
# for more info, go to https://yaml.org/