spring:
  datasource:
    url: jdbc:mysql://localhost:3307/SRM_dev
    username: SRM_dev_user
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true