# yet another markup language or YAML Ain't Markup Language, watch your spacing!
# Spring looks for application.properties and application.yaml (or application.yml) for Spring Boot properties
# YAML tends to be easier to read regarding data structures and used widely

# Enable a profiles (instead of spring.profiles.active=EN); change EN to/from DE to allow -EN or -DE to override
spring:
  profiles:
    active: EN

# equivalent to srmdatabase.customMessage=All credentials successfully loaded (this is the default if profiles
# are commented out)
srmdatabase:
  customMessage: "All good!"

---

# note that strings with special characters are best enclosed in " "
# for more info, go to https://yaml.org/